import { locale } from '@/theme-kit';

export function generateMetadata() {
    const localeCode = locale();
    return {
        title: `Stories homepage for ${localeCode}`,
        description: 'Generated by Next.js',
    };
}

interface Props {
    children: React.ReactNode;
}

export default function LocaleLayout({ children }: Props) {
    const localeCode = locale();
    return (
        <html>
            <body>
                <h1>{localeCode} locale layout</h1>
                {children}
            </body>
        </html>
    );
}
